# Generated by Django 5.0.12 on 2026-05-02 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(choices=[('rwanda', 'Rwanda'), ('kenya', 'Kenya'), ('tanzania', 'Tanzania')], help_text='Country of residence', max_length=50)),
                ('full_name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=20)),
                ('city', models.CharField(max_length=100)),
                ('dob', models.DateField(verbose_name='Date of Birth')),
                ('is_18', models.BooleanField(help_text='Applicant must be 18 or older', verbose_name='I confirm that I am 18 years or older')),
                ('status', models.CharField(choices=[('student', 'Student'), ('employed', 'Employed'), ('freelancer', 'Freelancer'), ('other', 'Other')], help_text='Current employment/student status', max_length=50)),
                ('field', models.CharField(help_text='Your field of study or professional field', max_length=255, verbose_name='Field of study or work')),
                ('python_level', models.CharField(choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced')], max_length=50, verbose_name='Python proficiency level')),
                ('python_duration', models.CharField(choices=[('lt_6m', '< 6 months'), ('6_12m', '6–12 months'), ('1_2y', '1–2 years'), ('2y_plus', '2+ years')], max_length=50, verbose_name='How long have you been using Python?')),
                ('why_attend', models.TextField(help_text='Tell us about your motivation for attending', verbose_name='Why do you want to attend PyCon Uganda?')),
                ('hope_to_gain', models.TextField(help_text='What skills, knowledge, or connections are you looking for?', verbose_name='What do you hope to gain from the conference?')),
                ('interests', models.CharField(help_text='e.g., AI/ML, Web Development, Data Science, Open Source, DevOps/Cloud', max_length=500, verbose_name='Areas of interest (comma-separated)')),
                ('community', models.TextField(blank=True, help_text='Optional: Tell us about your involvement in tech communities', null=True, verbose_name='Are you part of any community or organization?')),
                ('contributions', models.TextField(blank=True, help_text='Optional: Open source, mentoring, organizing events, etc.', null=True, verbose_name='How have you contributed to the tech community?')),
                ('knowledge_sharing', models.TextField(blank=True, help_text='Optional: Blogging, teaching, talks, etc.', null=True, verbose_name='How do you share knowledge with others?')),
                ('attend_all', models.BooleanField(help_text='Confirm your commitment to attend the full conference', verbose_name='I can attend all days of the conference')),
                ('represent_professionally', models.BooleanField(help_text='Agree to represent the event and community professionally', verbose_name='I will represent PyCon Uganda professionally')),
                ('share_publicly', models.BooleanField(help_text='Permission to share your experience on social media, etc.', verbose_name='I agree to share my experience publicly')),
                ('represent_how', models.CharField(blank=True, help_text='Optional: Social media, blog posts, presentations, etc.', max_length=500, null=True, verbose_name='How will you represent the event?')),
                ('has_national_id', models.BooleanField(help_text='Confirm you have a national ID', verbose_name='I have a valid national ID')),
                ('has_passport', models.BooleanField(help_text='Confirm you have a valid passport', verbose_name='I have a valid passport')),
                ('can_travel', models.BooleanField(help_text='Confirm you can get travel documents for attending', verbose_name='I can obtain travel documents if needed')),
                ('financial_support', models.CharField(choices=[('travel', 'Travel'), ('accommodation', 'Accommodation'), ('conference_ticket', 'Conference Ticket'), ('none', 'None')], help_text='Select the type of support you may need', max_length=100, verbose_name='Do you need financial support?')),
                ('anything_else', models.TextField(blank=True, help_text='Optional: Additional information about yourself', null=True, verbose_name="Anything else you'd like us to know?")),
                ('application_status', models.CharField(choices=[('submitted', 'Submitted'), ('reviewed', 'Reviewed'), ('accepted', 'Accepted'), ('rejected', 'Rejected')], default='submitted', help_text='Tracks the review status of the application', max_length=50, verbose_name='Application Status')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Application',
                'verbose_name_plural': 'Applications',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['-created_at'], name='diversity_a_created_a45bec_idx'), models.Index(fields=['application_status'], name='diversity_a_applica_8859d7_idx'), models.Index(fields=['email'], name='diversity_a_email_8832e3_idx')],
            },
        ),
    ]
