# Generated by Django 5.0.12 on 2026-05-02 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diversity_applications', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='application',
            name='anything_else',
        ),
        migrations.AddField(
            model_name='application',
            name='additional_notes',
            field=models.TextField(blank=True, help_text='Optional: Additional information about yourself', null=True, verbose_name='Additional notes'),
        ),
    ]
